### ISSUE TITLE
Where does this get uploaded to and where's my key?

### ISSUE THREAD

**Issue by eorroe** [dineshkumar-cse/ShareFile#1]
Hey I can't seem to find my key where is that? And to what server does this get uploaded to? Have you thought about making this work easily through the same network. I would love for this to work as so.

**Comment by eorroe** [comment]
So found my key, how do I delete the files? etc

**Comment by devdinu** [comment]
Hi, Use `ctrl + alt + r` key combination to remove a file from server.
- Currently the files are saved in "http://sharefiles-liveasdev.rhcloud.com/" a hosted server, I am thinking of it to make it more secure.
- Its a good thought to store in local User Defined server. Sure will add the feature in some time or would love to merge any pull requests.
- For others reference, have a look at `Defatult (OS.*).sublime-keymap` which have mappings.

```
[
    { "keys": ["ctrl+alt+u"], "command": "share_file" },
    { "keys": ["ctrl+alt+d"], "command": "download_file" },
    { "keys": ["ctrl+alt+r"], "command": "remove_file" }
]
```
- You can find the key in `ShareFiles.sublime-settings` in sublime Package Directory (eg: OSX: `~/Library/Application Support/Sublime Text 3/Packages/User`)

**Comment by eorroe** [comment]
Please add the `remove_file` to the command palette, and the settings under `preferences` -> `package control` -> `Share File` I already use those keybindings for something else so its conflicting. I rather use this from command palette

**Comment by eorroe** [comment]
The deleting did not show the files deleted until I restarted sublime, meaning the files were still showing in the list weird.

**Comment by dineshkumar-cse** [comment]
a70b37de8afbc281c3b2add67e87220721daf168 closes issue

**Comment by eorroe** [comment]
Actually the files don't delete at all for some reason, when I restarted it and checked I thought it did, they just took a while to show up again. Files are still there. I know this may not be that important of a project, but I just thought of this idea of easily sharing a file to someone from sublime, then found yours and gave it a try. But would be awesome if this could work locally.

**Comment by devdinu** [comment]
The issue was due to version mismatch in the hosted Backend Service **(openshift uses pymongo older version 2.5.2)** so the delete (api) wasn't working, Now i've redeployed the service with the fix. You can try now and let me know.

**Comment by eorroe** [comment]
Seems to work, but I'm wondering is there a web interface where I can see all those files? 1. Is trust. 2. Is just managing them that way would be really nice. I like this because I hate having to push to git all the time, for something that a colleague and I are sharing, I want to easily transfer a file to a computer, refactor something and then send it back to him for stuff like that. This is awesome.

**Comment by devdinu** [comment]
- Nope, There's no Web UI available for now, but building it might be easy as there is separate backend service. But i am mainly focusing on plugin as we code with sublime, just share it (I see it as a pain to share via mail or other mechanism). Its like i share key with my team and i upload it whenever its needed.
- Trust ? Are you talking about content hosted somewhere? to tackle we can encrypt & can add authentication for specific files. To host in intra network i can provide provisioning script, and the plugin can get the configured url from backend service.

Thanks @eorroe for trying it out and raising the issue.
